version: "3"
services:
# "db"というコンテナを定義
  db:
    # MySQLのイメージを指定
    image: mysql:5.6
    environment:
    # PasswordとUsernameはdatabase.ymlと合せる
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"

# "web"というコンテナを定義
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    # ローカルのディレクトリをマウント
    volumes:
      - .:/favorite-items
    ports:
      - "3000:3000"
    # appコンテナとdbコンテナを連携
    links:
      - db
